---

services:
  prometheus-exporter-acos:
    image: "ghcr.io/vveliev-tc/prometheus-exporter-acos:local"
    container_name: prometheus-exporter-acos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9734:9734"
    volumes:
      - ./src/:/app/
