---

services:
  prometheus-exporter-acos:
    image: "docker.io/vveliev-tc/prometheus-exporter-acos:local"
    container_name: prometheus-exporter-acos
    build:
      context: .
      target: ${TARGET:-development}
      dockerfile: Dockerfile
    ports:
      - "9734:9734"
    volumes:
      - ./src/:/app/
