---

services:
  prometheus-exporter-acos:
    image: "ghcr.io/vveliev-tc/prometheus-exporter-acos:local"
    container_name: prometheus-exporter-acos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9734:9734"
    command: ["acos_exporter.py", "--config", "/local/config.yml"]
    volumes:
      - ./examples/:/local/
      - ./src/:/app/
