# Example of a configuration file for ASOC prometheus exporter
---
hosts:
  <host_ip goes here>:
    username: <uname goes here>
    password: <pwd goes here>
log:
  log_level: DEBUG
  # log_file: /app/log/acos_exporter.log
